### ISSUE TITLE
Delaunay error.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [sakrist/BezierPath#1]
no such module called Delaunay.

How to resolve this error?

**Comment by sakrist** [comment]
You need to checkout with recursive submodules:
`git clone --recurse-submodules https://github.com/sakrist/BezierPath.git`

Delaunay is submodule repository and it's essential for triangulation in this sample. You can [find it](https://github.com/sakrist/Delaunay) in my repositories.
